---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: STRIPE_API_KEY
    value: ${STRIPE_API_KEY}
    type: text
  - name: CREDIT_API_KEY
    value: ${CREDIT_API_KEY}
    type: text
  - name: LEADS_API_KEY
    value: ${LEADS_API_KEY}
    type: text
  - name: TWILIO_ACCOUNT_SID
    value: ${TWILIO_ACCOUNT_SID}
    type: text
  - name: TWILIO_ACCOUNT_SECRET
    value: ${TWILIO_ACCOUNT_SECRET}
    type: text
  - name: TWILIO_PHONE_NUMBER
    value: ${TWILIO_PHONE_NUMBER}
    type: text
  jobs:
  - name: Build
    type: builder
    script: |-
      #!/bin/bash
      npm install -g npm@3.7.2 ### work around default npm 2.1.1 instability
      npm install
      npm run build
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared cloudant
      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
