---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: STRIPE_API_KEY
    value: ${STRIPE_API_KEY}
    type: text
  - name: CREDIT_API_KEY
    value: ${CREDIT_API_KEY}
    type: text
  - name: LEADS_API_KEY
    value: ${LEADS_API_KEY}
    type: text
  - name: TWILIO_ACCOUNT_SID
    value: ${TWILIO_ACCOUNT_SID}
    type: text
  - name: TWILIO_ACCOUNT_SECRET
    value: ${TWILIO_ACCOUNT_SECRET}
    type: text
  - name: TWILIO_PHONE_NUMBER
    value: ${TWILIO_PHONE_NUMBER}
    type: text
  jobs:
  - name: Build
    type: builder
    script: |-
      #!/bin/bash
      sed -ie "s/__STRIPE_API_KEY/$STRIPE_API_KEY/" manifest.yml
      sed -ie "s/__CREDIT_API_KEY/$CREDIT_API_KEY/" manifest.yml
      sed -ie "s/__LEADS_API_KEY/$LEADS_API_KEY/" manifest.yml
      sed -ie "s/__TWILIO_ACCOUNT_SID/$TWILIO_ACCOUNT_SID/" manifest.yml
      sed -ie "s/__TWILIO_ACCOUNT_SECRET/$TWILIO_ACCOUNT_SECRET/" manifest.yml
      sed -ie "s/__TWILIO_PHONE_NUMBER/$TWILIO_PHONE_NUMBER/" manifest.yml
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared cloudant
      # Push app
      if ! cf app $CF_APP; then  
        cf push $CF_APP
      else
        OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
        rollback() {
          set +e  
          if cf app $OLD_CF_APP; then
            cf logs $CF_APP --recent
            cf delete $CF_APP -f
            cf rename $OLD_CF_APP $CF_APP
          fi
          exit 1
        }
        set -e
        trap rollback ERR
        cf rename $CF_APP $OLD_CF_APP
        cf push $CF_APP
        cf delete $OLD_CF_APP -f
      fi
